# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e2cf2ee9bf04133616b651d8f7e35f9bccddae4ca9fba3db3f9bb5c065af85566a14c5518232ca1175794197ff9453401a1c27a558241efb1117861463a9ee1

test:
  secret_key_base: 6a8230ef613aa2bd96ace97dab4fd666895e9b9be98d9b6262a89eee890ca77f3a4e3bc268b315382e7163b7c882b72b4d66e603ca22c6233e473c2fcd6a6284

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
